version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - redmine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=redmine'
  redmine:
    image: renanlagee/redmine
    restart: always
    depends_on:
      - postgres
    networks:
      - redmine
    volumes:
     - redmine-data:/usr/src/redmine/files
     - ./redmine-plugins:/usr/src/redmine/plugins
    ports:
      - 3200:3000
    environment:
      - 'REDMINE_DB_POSTGRES=postgres'
      - 'REDMINE_DB_DATABASE=redmine'
      - 'REDMINE_DB_PASSWORD=password'
      - 'REDMINE_PLUGINS_MIGRATE=true'
      - 'REDMINE_PLUGINS_MIGRATE="yes"'
volumes:
  postgres-data:
  redmine-data:
networks:
  redmine:
    driver: bridge
